version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Ticket_Sales
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/Ticket_Sales
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm run dev
      "

volumes:
  pg_data:
